### ISSUE TITLE
missing usb_bindings.node?

### ISSUE THREAD

**Issue by EphDoering** [ravikp7/node-beagle-boot#29]
I got `npm install` to work via the instructions (+ adding libpcap-dev to the apt-get line) but when I try to start it via `npm start` I get teh following error:

```
> beagle-boot@1.2.1 start /home/debian/node-beagle-boot
> node runServer.js

internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module '/home/debian/node-beagle-boot/node_modules/usb/src/binding/usb_bindings.node'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/home/debian/node-beagle-boot/node_modules/usb/usb.js:5:38)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
```

**Comment by EphDoering** [comment]
This was an issue with the usb module. The usb module didn't support arm until a more recent version of node than I had installed. Resolved by upgrading my node version.
